=== Yuri6037/SJE2D/src/main/resources/app.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="minengine" xmlns="minengine"
           attributeFormDefault="unqualified" elementFormDefault="qualified">
  <xs:element name="app" type="appType"/>
  <xs:complexType name="displayType">
    <xs:sequence>
      <xs:element type="xs:string" name="title" minOccurs="0"/>
      <xs:element type="xs:short" name="width"/>
      <xs:element type="xs:short" name="height"/>
      <xs:element type="xs:boolean" name="fullscreen"/>
      <xs:element type="xs:boolean" name="vsync"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="assetsType">
    <xs:sequence>
      <xs:element type="registryType" name="registry"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="registryType">
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:element type="xs:string" name="protocol"/>
      <xs:element type="xs:string" name="factory"/>
    </xs:choice>
  </xs:complexType>
  <xs:complexType name="bindingType">
    <xs:sequence>
      <xs:element type="xs:string" name="id"/>
      <xs:element type="xs:string" name="key"/>
      <xs:element type="xs:string" name="modifier" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="bindingsType">
    <xs:sequence minOccurs="0" maxOccurs="unbounded">
      <xs:element type="bindingType" name="binding"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="axisType">
    <xs:sequence>
      <xs:element type="xs:string" name="id"/>
      <xs:element type="xs:string" name="key"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="axesType">
    <xs:sequence minOccurs="0" maxOccurs="unbounded">
      <xs:element type="axisType" name="axis"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="inputType">
    <xs:sequence>
      <xs:element type="xs:boolean" name="use-mouse"/>
      <xs:element type="xs:boolean" name="use-keyboard"/>
      <xs:element type="xs:boolean" name="use-joystick"/>
      <xs:element type="bindingsType" name="bindings"/>
      <xs:element type="axesType" name="axes"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="appType">
    <xs:sequence>
      <xs:element type="xs:string" name="name"/>
      <xs:element type="xs:string" name="version"/>
      <xs:element type="xs:float" name="speed" minOccurs="0"/>
      <xs:element type="displayType" name="display"/>
      <xs:element type="inputType" name="input"/>
      <xs:element type="assetsType" name="assets"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== Yuri6037/SJE2D/examples/fonts/src/main/resources/app.xml
<?xml version="1.0" encoding="UTF-8" ?>
<app xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="sje2d"
     xsi:schemaLocation="sje2d https://raw.githubusercontent.com/Yuri6037/SJE2D/main/src/main/resources/app.xsd">
    <name>Example App</name>
    <version>0.0.1</version>
    <display>
        <width>1024</width>
        <height>768</height>
        <fullscreen>false</fullscreen>
        <vsync>true</vsync>
    </display>
    <input>
        <use-mouse>false</use-mouse>
        <use-keyboard>false</use-keyboard>
        <use-joystick>false</use-joystick>
        <bindings>
        </bindings>
        <axes>
        </axes>
    </input>
    <assets>
        <registry>
            <factory>com.github.yuri6037.sje2d.asset.factory.ImageTextureFactory</factory>
            <factory>com.github.yuri6037.sje2d.asset.factory.FontFactory</factory>
            <factory>com.github.yuri6037.sje2d.asset.factory.FontBitmapFactory</factory>
            <protocol>com.github.yuri6037.sje2d.asset.protocol.ResourceProtocol</protocol>
            <protocol>com.github.yuri6037.sje2d.asset.protocol.FileProtocol</protocol>
            <protocol>com.github.yuri6037.sje2d.asset.protocol.HttpProtocol</protocol>
            <protocol>com.github.yuri6037.sje2d.asset.protocol.HttpsProtocol</protocol>
            <protocol>com.github.yuri6037.sje2d.asset.protocol.NoneProtocol</protocol>
        </registry>
    </assets>
</app>

=== Yuri6037/SJE2D/src/main/resources/example.xml
<?xml version="1.0" encoding="UTF-8" ?>
<app xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="sje2d"
     xsi:schemaLocation="sje2d https://github.com/Yuri6037/SJE2D/blob/main/src/main/resources/app.xsd">
    <name>Example App</name>
    <version>0.0.1</version>
    <display>
        <width>1600</width>
        <height>900</height>
        <fullscreen>false</fullscreen>
        <vsync>true</vsync>
    </display>
    <input>
        <use-mouse>true</use-mouse>
        <use-keyboard>true</use-keyboard>
        <use-joystick>false</use-joystick>
        <bindings>
            <binding>
                <id>quit</id>
                <key>ESCAPE</key>
                <modifier>MENU</modifier>
            </binding>
        </bindings>
        <axes>
            <axis>
                <id>cursor</id>
                <key>MOUSE</key>
            </axis>
        </axes>
    </input>
    <assets>
        <registry>
            <factory>com.github.yuri6037.sje2d.test.asset.TestLoader.Factory</factory>
            <protocol>com.github.yuri6037.sje2d.test.asset.TestProtocol</protocol>
        </registry>
    </assets>
</app>
