=== Yuri6037/SJE2D/src/main/resources/font.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="sje2d" xmlns="sje2d"
           attributeFormDefault="unqualified" elementFormDefault="qualified">
  <xs:element name="font" type="fontType"/>
  <xs:complexType name="baseType" mixed="true">
    <xs:sequence>
      <xs:element type="xs:string" name="family"/>
      <xs:element type="xs:string" name="size"/>
      <xs:element type="xs:string" name="italic"/>
      <xs:element type="xs:string" name="bold"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="type"/>
  </xs:complexType>
  <xs:complexType name="ruleType" mixed="true">
    <xs:sequence>
      <xs:element type="xs:string" name="family" minOccurs="0"/>
      <xs:element type="xs:string" name="size" minOccurs="0"/>
      <xs:element type="xs:string" name="italic" minOccurs="0"/>
      <xs:element type="xs:string" name="bold" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="min" use="required"/>
    <xs:attribute type="xs:string" name="max" use="required"/>
    <xs:attribute type="xs:string" name="type" use="required"/>
  </xs:complexType>
  <xs:complexType name="rulesType">
    <xs:sequence>
      <xs:element type="ruleType" name="rule" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="fontType">
    <xs:sequence>
      <xs:element type="xs:string" name="name"/>
      <xs:element type="xs:string" name="width"/>
      <xs:element type="baseType" name="base"/>
      <xs:element type="rulesType" name="rules"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== Yuri6037/SJE2D/src/main/resources/font.xml
<?xml version="1.0" encoding="UTF-8" ?>
<font xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="sje2d"
      xsi:schemaLocation="sje2d https://github.com/Yuri6037/SJE2D/blob/main/src/main/resources/font.xsd">
    <name>Default</name>
    <width>1024</width>
    <base>
        <system>
            <family>Default</family>
            <size>12</size>
            <italic>false</italic>
            <bold>false</bold>
        </system>
    </base>
    <rules>
        <rule min="1F601" max="1F64F">
            <system>
                <family>Noto</family>
                <size>12</size>
                <italic>false</italic>
                <bold>false</bold>
            </system>
        </rule>
    </rules>
</font>

=== Yuri6037/SJE2D/examples/fonts/src/main/resources/font.xml
<?xml version="1.0" encoding="UTF-8" ?>
<font xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="sje2d"
      xsi:schemaLocation="sje2d https://github.com/Yuri6037/SJE2D/blob/main/src/main/resources/font.xsd">
    <name>Default</name>
    <width>512</width>
    <base>
        <family>Default</family>
        <size>24</size>
        <italic>false</italic>
        <bold>false</bold>
    </base>
    <rules>
        <rule min="1F600" max="1F64F">
            <url>https://fonts.gstatic.com/s/notoemoji/v39/bMrnmSyK7YY-MEu6aWjPDs-ar6uWaGWuob_10jwv.ttf</url>
            <size>20</size>
            <italic>false</italic>
            <bold>true</bold>
        </rule>
    </rules>
</font>
